### ISSUE TITLE
c3 is not defined

### ISSUE THREAD

**Issue by Dyzmj** [aliyun/aliyun-cms-grafana#13]
granfana使用的是v5.3.4，监控RDS服务，点击Save & Test按钮 ,状态一直显示Testing, F12控制台报错 【c3 is not defined 】；
切换最新版本的grafana 6.5.1，点击Save & Test按钮页面直接报错【c3 is not defined】

**Comment by roymax** [comment]
AK 要base64 一下

**Comment by keliangneu** [comment]
> AK 要base64 一下

ak base64了还是提示同样的错误

**Comment by keliangneu** [comment]
> AK 要base64 一下

Commits on Mar 6, 2019 这个版本是可以的，12月份更新后就不行了

**Comment by keliangneu** [comment]
ID和key都base64的情况下, 提示 HTTP error not found

**Comment by keliangneu** [comment]
解决了，去掉用base64命令生成的key最后字符‘Cg==’。

**Comment by keliangneu** [comment]
@Dyzmj

**Comment by Dyzmj** [comment]
谢谢，可以解决问题
