### ISSUE TITLE
ReferenceError: c3 is not defined

### ISSUE THREAD

**Issue by dolphin-blue** [aliyun/aliyun-cms-grafana#15]
报c3未定义错误原因：
![1576719745(1)](https://user-images.githubusercontent.com/30971335/71137940-c6ffe100-2244-11ea-8b99-59c6e16cc4db.jpg)
decode_text乱码导致c3处抛异常

**Comment by ItShines** [comment]
AK输入验证增加BASE64加解密功能，防止明码AK。后续持续优化；
更新后，需要对输入的AK进行BASE64一下，文档9、20191030更新内容有标注
