### ISSUE TITLE
CMS Grafana Service 插件获取PostgreSQL只能显示一个

### ISSUE THREAD

**Issue by uranus321** [aliyun/aliyun-cms-grafana#17]
CMS Grafana Service 插件获取PostgreSQL的时候有group及primary的指标，但只能显示一个，能否改善一下呢？
![99](https://user-images.githubusercontent.com/58728442/74213654-2de5c780-4cd5-11ea-965f-7f0c2465a451.jpg)

**Comment by ItShines** [comment]
这个是它本身的dimension如此，https://help.aliyun.com/document_detail/28619.html?spm=a2c4g.11186623.6.688.989656790OP2l2#title-zj5-g24-v0l

**Comment by uranus321** [comment]
我已经找到方法可以显示了，感谢，如果可以支持实例名称就好了！

**Comment by ItShines** [comment]
实例名称和dimension暂未打通，毕竟有的dimension不需要instanceId，所以这个实现比较困难

**Comment by uranus321** [comment]
或者在插件上做一个关联显示，这样就可以显示名称出来了。

**Comment by uranus321** [comment]
@ItShines 请问CMS Grafana 切换到 last 1 hour，有些图标就没有data了，是不是阿里云限流了啊？
![00](https://user-images.githubusercontent.com/58728442/74299580-1582b500-4d88-11ea-8e87-6523dc2cf26e.png)
