### ISSUE TITLE
刷新数据提示no data,开发者工具提示400(BAD Request)

### ISSUE THREAD

**Issue by uranus321** [aliyun/aliyun-cms-grafana#18]
1、单个图表view，然后刷新是可以显示出来的，只要整个网页刷新就加载不全。
2、请阿里开发帮看下什么原因？谢谢
![00](https://user-images.githubusercontent.com/58728442/74313303-673e3600-4dae-11ea-9782-0064370c3902.png)
![no data](https://user-images.githubusercontent.com/58728442/74313316-6e654400-4dae-11ea-8ef8-b599a80fab2b.jpg)
![nodata2](https://user-images.githubusercontent.com/58728442/74313741-3d394380-4daf-11ea-930a-eaf34ea383e5.jpg)

**Comment by ItShines** [comment]
一下加载太多，被API限流了，所以访问失败，导致数据刷新不出来；可以支持20个左右的dashboard，建议使用row，或多个dashboard，或者模板功能

**Comment by uranus321** [comment]
row及模板的功能有指引吗？

**Comment by ItShines** [comment]
row就是添加panel的时候有个row，可以控制显示；模板就是variable，点击设置里面有，具体可以看看readme文档

**Comment by uranus321** [comment]
我刚试了一下,18个panel还是有这个情况啊！

**Comment by uranus321** [comment]
我看别人的监控中心那么多panel都没问题呢？
![001](https://user-images.githubusercontent.com/58728442/74329763-610a8280-4dcb-11ea-8285-7fa62af79034.jpg)

**Comment by ItShines** [comment]
api有限流，超阈值后，直接就不返回bad request了，

**Comment by uranus321** [comment]
求阿里，api能否可以提高？或者还有其它方法吗？

**Comment by ItShines** [comment]
尽量控制每个页面的panel数，多建几个dashboard；或者同个dashboard使用多个row，

**Comment by uranus321** [comment]
@ItShines 再请问一下,访问metrics.cn-hongkong.aliyuncs.com 香港站，是否网络不支持连通？怎么测试HTTP失败呢？

**Comment by jinxiao** [comment]
我四个pannel都出现问题，阿里云这个功能做的太差了

**Comment by ItShines** [comment]
http://metrics.cn-hongkong.aliyuncs.com

**Comment by jinxiao** [comment]
> @ItShines 再请问一下,访问metrics.cn-hongkong.aliyuncs.com 香港站，是否网络不支持连通？怎么测试HTTP失败呢？我在服务器上ping是通的。
> ![77](https://user-images.githubusercontent.com/58728442/74498903-0c771c80-4f1d-11ea-8326-ea001db42080.jpg)

我使用的是北京区，已经提case解决，后台做了处理才解决
