### ISSUE TITLE
tagFilter和tag变量Bug?

### ISSUE THREAD

**Issue by duliang123** [aliyun/aliyun-cms-grafana#21]
Query设置：tagFilter(ecs,cn-hangzhou,value,null)
提示：
Template variables could not be initialized: undefined

Data_Sources是正常的

**Comment by duliang123** [comment]
![image](https://user-images.githubusercontent.com/22148752/76699141-4cc8e680-66e5-11ea-935f-9a7381447ed6.png)

**Comment by duliang123** [comment]
![image](https://user-images.githubusercontent.com/22148752/76699151-5f432000-66e5-11ea-8bab-5d87d9a1200e.png)

**Comment by ylmcr7** [comment]
我也出现了这个问题。你的解决了吗。怎么解决的
