### ISSUE TITLE
cmsAccessKey和secret不应该放在jsonData字段里，会被前端直接明文读取

### ISSUE THREAD

**Issue by crackerben** [aliyun/aliyun-cms-grafana#42]
/api/datasources 查看所有
/api/datasources/{id} 查看单个

**Comment by adolli** [comment]
## 我遇到的问题

用cms插件对接阿里云监控数据时，任意用户可以在grafana前端获取AK，造成AK泄露，这与README中描述不符

https://github.com/aliyun/aliyun-cms-grafana/blame/master/README.md#L17-L18


## 我如何发现的？

在了解了grafana DataSource proxy的基本逻辑后

1. 发现aliyun cms查询实际上是一个pre-signed url，并且pre-signed url是需要AccessKey+SecretKey共同来sign的
2. grafana的plugin系统在后端并没有提供业务自定义逻辑，因此只能由前端完成url签名的操作

通过以上两条已知条件，可推出AK必然传到了前端。

### 发现的步骤

1. 在AK会传到前端的假设下，在前端js中搜对应的AK字符串，可发现对应的变量含有此值，验证了以上假设

![image](https://user-images.githubusercontent.com/8390109/105636181-24338080-5ea2-11eb-818e-741cdbed185a.png)

2. 在grafana的代码中进一步追踪发现，`index-template.html`的渲染中传递了所有data sources相关的配置信息，其中jsonData是明文传递的。

前端  
https://github.com/grafana/grafana/blob/2a21f067b71979c5c4a45296dcd5781766229133/public/views/index-template.html#L224-L230

后端  
https://github.com/grafana/grafana/blob/2a21f067b71979c5c4a45296dcd5781766229133/pkg/api/http_server.go#L331-L335

### 导致的安全问题

任意用户(无需授权任何面板)只要进入了grafana，就能直接在浏览器中获得所有data sources 的配置信息，在console中访问以下值

```js
window.grafanaBootData.settings.datasources
```

## 如何避免这个问题？

可能可以使用grafana backend plugin实现，参考 [backend plugin doc](https://grafana.com/docs/grafana/latest/developers/plugins/backend/#use-cases-for-implementing-a-backend-plugin)

**Comment by yichangtian** [comment]
谢谢 adolli，我们已经发了新版本 V2.0，支持backend plugin了。

**Comment by adolli** [comment]
> 谢谢 adolli，我们已经发了新版本 V2.0，支持backend plugin了。

请问下有链接吗？

**Comment by yichangtian** [comment]
https://github.com/aliyun/aliyun-cms-grafana/releases

**Comment by adolli** [comment]
感谢
