### ISSUE TITLE
Data source is not working

### ISSUE THREAD

**Issue by clot09** [aliyun/aliyun-cms-grafana#49]
- 环境：
1. grafana 6.6.2
2. aliyun-cms-grafana v2.0

- 问题:
在添加数据源的时候，报Data source is not working，grafana 日志里面没任何报错

- 启动日志无异常:

```shell
t=2021-03-29T11:34:00+0000 lvl=dbug msg="Serving plugin" logger=plugins.backend pluginId=aliyun_cms_grafana_datasource plugins="[diagnostics resource]"
t=2021-03-29T11:34:00+0000 lvl=dbug msg="plugin address" logger=plugins.backend pluginId=aliyun_cms_grafana_datasource network=unix address=/tmp/plugin572284246
t=2021-03-29T11:34:00+0000 lvl=dbug msg="using plugin" logger=plugins.backend pluginId=aliyun_cms_grafana_datasource version=2
t=2021-03-29T11:34:00+0000 lvl=dbug msg="Registering metrics collector" logger=plugins.backend pluginId=aliyun_cms_grafana_datasource
t=2021-03-29T11:34:00+0000 lvl=dbug msg="Browser initialized" logger=plugins.backend pluginId=grafana-image-renderer config="map[args:[--no-sandbox] chromeBin:/var/lib/grafana/plugins/grafana-image-renderer/chrome-linux/chrome clustering:map[maxConcurrency:5 mode:browser] deviceScaleFactor:1 dumpio:false height:500 ignoresHttpsErrors:false maxDeviceScaleFactor:3 maxHeight:3000 maxWidth:3000 mode:default verboseLogging:false width:1000]"
```
<img width="1463" alt="cms_error" src="https://user-images.githubusercontent.com/4077252/112831521-a1f45200-90c6-11eb-8d2b-1ae0354f33ef.png">

- 进程状态
```shell
bash-5.0$ ps -ef|grep cms
   23 grafana   0:00 /var/lib/grafana/plugins/aliyun_cms_grafana_datasource/dist/cms-datasource_linux_amd64
   50 grafana   0:00 grep cms
```

**Comment by clot09** [comment]
`t=2021-03-29T11:34:00+0000 lvl=dbug msg="Serving plugin" logger=plugins.backend pluginId=aliyun_cms_grafana_datasource plugins="[diagnostics resource]"
t=2021-03-29T11:34:00+0000 lvl=dbug msg="plugin address" logger=plugins.backend pluginId=aliyun_cms_grafana_datasource network=unix address=/tmp/plugin572284246
t=2021-03-29T11:34:00+0000 lvl=dbug msg="using plugin" logger=plugins.backend pluginId=aliyun_cms_grafana_datasource version=2
t=2021-03-29T11:34:00+0000 lvl=dbug msg="Registering metrics collector" logger=plugins.backend pluginId=aliyun_cms_grafana_datasource
t=2021-03-29T11:34:00+0000 lvl=dbug msg="Browser initialized" logger=plugins.backend pluginId=grafana-image-renderer config="map[args:[--no-sandbox] chromeBin:/var/lib/grafana/plugins/grafana-image-renderer/chrome-linux/chrome clustering:map[maxConcurrency:5 mode:browser] deviceScaleFactor:1 dumpio:false height:500 ignoresHttpsErrors:false maxDeviceScaleFactor:3 maxHeight:3000 maxWidth:3000 mode:default verboseLogging:false width:1000]"`

**Comment by tabniu** [comment]
+1

**Comment by fcmxmk** [comment]
+1

**Comment by fcmxmk** [comment]
@clot09 @tabniu 

![image](https://user-images.githubusercontent.com/24162498/153352185-3f10f0fb-bea9-4ac2-9961-0097d3c0c6ff.png)
